stages:
  - build
  - notify

build-image:
  stage: build
  image: docker:20.10.18-git
  # See: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker
  # For stateless builds, a sidecar dockerd service is needed
  # For stateful builds (i.e. DOCKER_HOST=unix:///var/run/docker.sock mounted from the host), a sidecar dockerd service is not needed
  # services:
  #   - docker:20.10.18-dind
  variables:
    DOCKER_DRIVER: overlay2
  rules:
    # Run on all branches except master, when .trigger is added or modified
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "master"
      changes:
        - .trigger
  timeout: 120m
  script:
    - |
      set +e
      ./build.sh
      if [ $? = 0 ]; then
          echo BUILD_STATUS=success >> .build.state
      else
          echo BUILD_STATUS=failed >> .build.state
          exit 1
      fi
  artifacts:
    name: .build.state-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
    paths:
      - .build.state
    when: always
    expire_in: never

notify:
  stage: notify
  image: alpine:3.15
  rules:
    # Run on all branches except master, when .trigger is added or modified
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "master"
      changes:
        - .trigger
  when: always
  timeout: 5m
  script:
    - apk add --no-cache curl
    - ./notify.sh
