version: '2.2'
services:
  srcds-csgo:
    image: sourceservers/csgo:latest
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    stdin_open: true
    tty: true
    entrypoint:
      - srcds_linux
    command:
      - -game csgo -ip 0.0.0.0 -port 27015 -maxplayers 16 +game_type 0 +game_mode 1 +mapgroup mg_active +map de_dust2

  srcds-hl2mp:
    image: sourceservers/hl2mp:latest
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    stdin_open: true
    tty: true
    entrypoint:
      - srcds_linux
    command:
      - -game hl2mp -ip 0.0.0.0 -port 27015 -maxplayers 16 +map dm_lockdown

  srcds-left4dead2:
    image: sourceservers/left4dead2:latest
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp
    stdin_open: true
    tty: true
    entrypoint:
      - srcds_linux
    command:
      - -game left4dead2 -ip 0.0.0.0 -port 27015 +map "c2m1_highway coop"

  hlds-cstrike:
    image: goldsourceservers/cstrike:latest
    ports:
      - 27015:27015/udp
    stdin_open: true
    tty: true
    entrypoint:
      - hlds_linux
    command:
      - -game cstrike +ip 0.0.0.0 +port 27015 +map de_dust2 +maxplayers 16

  hlds-czero:
    image: goldsourceservers/czero:latest
    ports:
      - 27015:27015/udp
    stdin_open: true
    tty: true
    entrypoint:
      - hlds_linux
    command:
      - -game czero +ip 0.0.0.0 +port 27015 +map de_dust2_cz +maxplayers 16

  hlds-valve:
    image: goldsourceservers/valve:latest
    ports:
      - 27015:27015/udp
    stdin_open: true
    tty: true
    entrypoint:
      - hlds_linux
    command:
      - -game valve +ip 0.0.0.0 +port 27015 +map boot_camp +maxplayers 16
