name: ci-master-pr

on:
  push:
    branches:
    - master
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  test-build-hlds:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        . ./test/build-hlds-cstrike.env
        . ./build.sh

  test-update-hlds:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        . ./test/update-hlds-cstrike.env
        . ./build.sh

  test-build-srcds:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        . ./test/build-srcds-hl2mp.env
        . ./build.sh

  test-update-srcds:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: |
        . ./test/update-srcds-hl2mp.env
        . ./build.sh
